export const campaignStyles = {
  overlay: { position: 'fixed', top: 0, left: 0, right: 0, bottom: 0, background: 'rgba(0,0,0,0.6)', display: 'flex', justifyContent: 'center', alignItems: 'center', zIndex: 1400 },
  modal: { background: '#fff', borderRadius: '14px', width: '92%', maxWidth: '540px', maxHeight: '88vh', display: 'flex', flexDirection: 'column', fontFamily: 'Tahoma, sans-serif' },
  header: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '12px 16px', borderBottom: '1px solid #eee' },
  closeBtn: { border: 'none', background: 'none', fontSize: '18px', cursor: 'pointer' },
  adminBtn: { background: '#f1f5f9', border: '1px solid #cbd5e1', padding: '4px 8px', borderRadius: '6px', fontSize: '11px', cursor: 'pointer' },
  appSupportHeaderBtn: { background: '#fef3c7', border: '1px solid #f59e0b', color: '#b45309', padding: '4px 8px', borderRadius: '6px', fontSize: '11px', fontWeight: 'bold', cursor: 'pointer' },
  langSelect: { padding: '3px 6px', borderRadius: '6px', border: '1px solid #cbd5e1', fontSize: '11px', background: '#f8fafc', cursor: 'pointer' },
  adminForm: { padding: '8px 15px', background: '#f8fafc', display: 'flex', gap: '8px' },
  statusBar: { padding: '8px 12px', fontSize: '11px', textAlign: 'center', fontWeight: 'bold', background: '#f8fafc', borderBottom: '1px solid #eee' },
  tabContainer: { display: 'flex', borderBottom: '1px solid #eee', background: '#f8fafc', overflowX: 'auto' },
  tab: { flex: 1, padding: '10px 4px', border: 'none', background: 'none', cursor: 'pointer', fontSize: '11px', fontWeight: 'bold', whiteSpace: 'nowrap' },
  body: { padding: '15px', overflowY: 'auto' },
  list: { display: 'flex', flexDirection: 'column', gap: '10px' },
  card: { background: '#f8fafc', border: '1px solid #e2e8f0', borderRadius: '8px', padding: '10px', fontSize: '12px', transition: 'all 0.3s ease' },
  activePlayingCard: { borderColor: '#10b981', boxShadow: '0 0 10px rgba(16, 185, 129, 0.2)' },
  badge: { background: '#10b981', color: '#fff', padding: '2px 6px', borderRadius: '4px', fontSize: '10px', fontWeight: 'bold' },
  desc: { color: '#64748b', fontSize: '11px', margin: '4px 0 8px 0' },
  shareBtn: { flex: 2, padding: '6px', background: '#0284c7', color: '#fff', border: 'none', borderRadius: '6px', cursor: 'pointer', fontSize: '11px', fontWeight: 'bold' },
  campaignSupportBtn: { flex: 1, padding: '6px', background: '#10b981', color: '#fff', border: 'none', borderRadius: '6px', cursor: 'pointer', fontSize: '11px', fontWeight: 'bold' },
  btn: { flex: 1, color: '#fff', border: 'none', padding: '6px', borderRadius: '4px', fontSize: '11px', cursor: 'pointer', fontWeight: 'bold' },
  form: { display: 'flex', flexDirection: 'column', gap: '8px', fontSize: '12px' },
  input: { padding: '8px', borderRadius: '6px', border: '1px solid #ccc', width: '100%' },
  textarea: { padding: '8px', borderRadius: '6px', border: '1px solid #ccc', fontFamily: 'sans-serif', width: '100%' },
  select: { padding: '8px', borderRadius: '6px', border: '1px solid #ccc', width: '100%', fontSize: '11px' },
  submitBtn: { padding: '10px', background: '#10b981', color: '#fff', border: 'none', borderRadius: '6px', cursor: 'pointer', fontWeight: 'bold', marginTop: '8px' },
  errorText: { color: '#dc2626', textAlign: 'center', fontSize: '12px', padding: '20px' },
  warningText: { color: '#d97706', textAlign: 'center', fontSize: '12px', padding: '20px' }
};